# Sample .travis.yml for R projects.
#
# See https://github.com/craigcitro/r-travis
#     https://github.com/eddelbuettel/r-travis/

language: c

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=FALSE

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh install_r Rcpp 
  - ./travis-tool.sh install_r BH

script:
#  - ./travis-tool.sh run_tests
  - echo "Now now: ./travis-tool.sh run_tests" && exit 0

# after_script:
#   - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change

