// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/RcppStreams.h"
#include <Rcpp.h>

using namespace Rcpp;

// commonSubexpressions
bool commonSubexpressions();
RcppExport SEXP RcppStreams_commonSubexpressions() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(commonSubexpressions());
    return __result;
END_RCPP
}
// helloStream
bool helloStream();
RcppExport SEXP RcppStreams_helloStream() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(helloStream());
    return __result;
END_RCPP
}
// crossAlert
bool crossAlert(int f1, int f2);
RcppExport SEXP RcppStreams_crossAlert(SEXP f1SEXP, SEXP f2SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type f1(f1SEXP);
    Rcpp::traits::input_parameter< int >::type f2(f2SEXP);
    __result = Rcpp::wrap(crossAlert(f1, f2));
    return __result;
END_RCPP
}
// slidingWindow
bool slidingWindow();
RcppExport SEXP RcppStreams_slidingWindow() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(slidingWindow());
    return __result;
END_RCPP
}
