// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// commonSubexpressions
bool commonSubexpressions();
RcppExport SEXP RcppStreams_commonSubexpressions() {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        bool __result = commonSubexpressions();
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// helloStream
bool helloStream();
RcppExport SEXP RcppStreams_helloStream() {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        bool __result = helloStream();
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// crossAlert
bool crossAlert(int f1, int f2);
RcppExport SEXP RcppStreams_crossAlert(SEXP f1SEXP, SEXP f2SEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< int >::type f1(f1SEXP );
        Rcpp::traits::input_parameter< int >::type f2(f2SEXP );
        bool __result = crossAlert(f1, f2);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// slidingWindow
bool slidingWindow();
RcppExport SEXP RcppStreams_slidingWindow() {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        bool __result = slidingWindow();
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
