# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' This is an example function illustrating Streamulus
#'
#' @title Common 'greeting' carried across several expressions
#' @return An unconditional TRUE value
#' @author Dirk Eddelbuettel
#' @examples commonSubexpressions()
commonSubexpressions <- function() {
    .Call(`_RcppStreams_commonSubexpressions`)
}

#' This is an example function illustrating Streamulus
#'
#' @title Print some hello messages
#' @return An unconditional TRUE value
#' @author Dirk Eddelbuettel
#' @examples helloStream()
helloStream <- function() {
    .Call(`_RcppStreams_helloStream`)
}

#' This is an example function illustrating Streamulus
#'
#' @title Alert for cross of two moving averages
#' @param f1 Parameter for the slower exponential moving average
#' @param f2 Parameter for the faster exponential moving average
#' @return An unconditional TRUE value
#' @author Dirk Eddelbuettel
#' @examples crossAlert(10,20)
crossAlert <- function(f1, f2) {
    .Call(`_RcppStreams_crossAlert`, f1, f2)
}

#' This is an example function illustrating Streamulus
#'
#' @title Sliding window function example
#' @return An unconditional TRUE value
#' @author Dirk Eddelbuettel
#' @examples slidingWindow()
slidingWindow <- function() {
    .Call(`_RcppStreams_slidingWindow`)
}

