# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' This is an example function illustrating Streamulus
#'
#' @title Print some hello messages
#' @param ignored Just to supply a parameter
#' @return An unconditional TRUE value
#' @author Dirk Eddelbuettel
helloStream <- function(ignored) {
    .Call('RcppStreams_helloStream', PACKAGE = 'RcppStreams', ignored)
}

#' This is am example function illustrating Streamulus
#'
#' @title Alert for cross of two moving averages
#' @param f1 Parameter for the slower exponential moving average
#' @param f2 Parameter for the faster exponential moving average
#' @return An unconditional TRUE value
#' @author Dirk Eddelbuettel
crossAlert <- function(f1, f2) {
    .Call('RcppStreams_crossAlert', PACKAGE = 'RcppStreams', f1, f2)
}

